//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ima
    {
        public int MlinIdMlina { get; set; }
        public int SkladisteIdSkladista { get; set; }
    
        public virtual Mlin Mlin { get; set; }
        public virtual Skladiste Skladiste { get; set; }
        public virtual Kamion Kamion { get; set; }
    }
}
