//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoljoprivrednaFirmaContainer : DbContext
    {
        public PoljoprivrednaFirmaContainer()
            : base("name=PoljoprivrednaFirmaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Psenica> Psenicas { get; set; }
        public virtual DbSet<TestKvaliteta> TestKvalitetas { get; set; }
        public virtual DbSet<Testira> Testiras { get; set; }
        public virtual DbSet<Prihvata> Prihvatas { get; set; }
        public virtual DbSet<Silos> Silos { get; set; }
        public virtual DbSet<Mlin> Mlins { get; set; }
        public virtual DbSet<Prekrupac> Prekrupacs { get; set; }
        public virtual DbSet<Poseduje> Posedujes { get; set; }
        public virtual DbSet<Brasno> Brasnoes { get; set; }
        public virtual DbSet<Pravi> Pravis { get; set; }
        public virtual DbSet<Uzima> Uzimas { get; set; }
        public virtual DbSet<Skladiste> Skladistes { get; set; }
        public virtual DbSet<Ima> Imas { get; set; }
        public virtual DbSet<Kamion> Kamions { get; set; }
    }
}
