//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poseduje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poseduje()
        {
            this.Odrzavateljs = new HashSet<Odrzavatelj>();
        }
    
        public int MlinIdMlina { get; set; }
        public int PrekrupacIdPrekrupaca { get; set; }
    
        public virtual Mlin Mlin { get; set; }
        public virtual Prekrupac Prekrupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odrzavatelj> Odrzavateljs { get; set; }
    }
}
