//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prihvata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prihvata()
        {
            this.Silos = new HashSet<Silos>();
        }
    
        public int PrijemnikJMBG { get; set; }
        public int TestiraPsenicaIdPsenice { get; set; }
        public int TestiraTestKvalitetaIdTesta { get; set; }
    
        public virtual Prijemnik Prijemnik { get; set; }
        public virtual Testira Testira { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Silos> Silos { get; set; }
    }
}
