//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Silos
    {
        public int IdSilosa { get; set; }
        public double KapacitetSilosa { get; set; }
        public bool PopunjenKapacitetS { get; set; }
    
        public virtual Mlin Mlin { get; set; }
        public virtual Prihvata Prihvata { get; set; }
        public virtual Prekrupac Prekrupac { get; set; }
    }
}
