//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzima()
        {
            this.Skladistes = new HashSet<Skladiste>();
        }
    
        public int MagacionerJMBG { get; set; }
        public int PraviPrekrupacIdPrekrupaca { get; set; }
        public int PraviBrasnoIdBrasna { get; set; }
    
        public virtual Magacioner Magacioner { get; set; }
        public virtual Pravi Pravi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skladiste> Skladistes { get; set; }
    }
}
